
steps:

# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Install tfjs-converter dependencies.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build-ci']
  waitFor: ['yarn', 'build-deps']

# Lint.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn', 'build-deps']

# Run python tests.
- name: 'gcr.io/google-appengine/python'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  id: 'test-python-pip'
  args: ['./build-pip-package.sh', '--test', '/tmp/tfjs-pips']
  waitFor: ['yarn-common']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'N1_HIGHCPU_8'
